### ISSUE TITLE
IOS Emulator error

### ISSUE THREAD

**Issue by fsciuti** [bradmartin/nativescript-checkbox#5] opened 2016-08-18 22:14 UTC
App crash when i run with: _tns livesync ios --emulator --watch_

Only message is "Service exited due to signal: Segmentation fault: 11"

**Comment by bradmartin** [comment] 2016-08-18 22:29
Thanks. I'll try to run it tonight and get a fix pushed if anything is wrong with the code. Are you running the demo?

**Comment by fsciuti** [comment] 2016-08-18 22:42
Sorry but i don't try the demo! :S

**Comment by bradmartin** [comment] 2016-08-19 03:07
@fsciuti I can't reproduce this error, I cloned the repo, added iOS to the demo and ran it with no issues on the simulator. Something else must be going on. If you aren't on the NativeScript slack channel you might want to jump in there and see if anyone else has any issues, but I've pinged a couple other devs who are actively using it and haven't seen any issues with it like this. You might just need to reset things, so run the `tns platform ios clean` command and then a new build and see if that clears things up.

**Comment by bnussey** [comment] 2016-08-20 04:41
Hey @bradmartin I was able to replicate this error but clicking on the name as opposed to the checkbox in iOS.

**Comment by sitefinitysteve** [comment] 2016-08-21 14:25
I found a weird case where it'd cause Segmentation 11 fault, send a PR https://github.com/bradmartin/nativescript-checkbox/pull/6

**Comment by fsciuti** [comment] 2016-08-23 08:05
Great @sitefinitysteve!

**Comment by bradmartin** [comment] 2016-08-24 16:00
Published 1.4  with PR #6

**Comment by bnussey** [comment] 2016-08-24 18:41
Hey @bradmartin  and @sitefinitysteve after updating, I am still getting a `Segmentation fault: 11` when clicking on the text next to the checkbox. here is the code:

`<CheckBox [text]="item.name" [checked]="item.onInviteList" (tap)="onContactTap(i)" class="field-title"></CheckBox>`

**Comment by sitefinitysteve** [comment] 2016-08-24 18:43
@bnussey Can you share your CSS that would relate to the checkbox?

**Comment by bnussey** [comment] 2016-08-24 18:48
hey @sitefinitysteve thanks for the quick response.. absolutely:

```
CheckBox {
    font-weight: bold;
    font-size: 14;
    color: black;
    margin: 2%, 0, 2%, 2%;
}
```

**Comment by sitefinitysteve** [comment] 2016-08-24 18:49
Thx thx, Ill get to trying to replicate... I mean can't replicate the NG2 stuff, so hopefully unrelated

**Comment by bnussey** [comment] 2016-08-24 18:49
Yeah hope so.. seems to work fine though when clicking the checkbox itself, its just the text.

**Comment by bradmartin** [comment] 2016-09-15 15:19
Does 1.1.5 fix this?

**Comment by sitefinitysteve** [comment] 2016-09-15 15:20
Unsure just yet... trying the ListView first

**Comment by sitefinitysteve** [comment] 2016-09-15 15:42
Okay so in the demo app in NS 2.3 there's no segmentation faults or anything... not sure about NG2 though still, pure TS\JS it appears to be fine?

**Comment by sitefinitysteve** [comment] 2016-09-15 20:22
So guys, I created a new project (not demo) and I also get this Seg11 fault, I am unsure why yet though... makes no sense to me, but can replicate...

**Comment by andy-tai** [comment] 2016-10-23 07:01
On Nativescript 2.3 with Angular 2.0, running the demo program on iOS simulator:

getting this crash:

Oct 22 23:54:51 Li-Chengs-Mini demo[1283]: assertion failed: 16A323 14A345: libxpc.dylib + 62597 [37A9DF49-35C1-3D93-B854-B35CACF0100F]: 0x7d
Oct 22 23:54:52 Li-Chengs-Mini demo[1283]: 1   0x10de80379 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
Oct 22 23:54:52 Li-Chengs-Mini demo[1283]: 2   0x10e4ed51e ffi_closure_unix64_inner
Oct 22 23:54:52 Li-Chengs-Mini demo[1283]: 3   0x10e4eded2 ffi_closure_unix64
Oct 22 23:54:52 Li-Chengs-Mini demo[1283]: 4   0x10f1e44a0 -[UIViewController view]
Oct 22 23:54:52 Li-Chengs-Mini demo[1283]: 5   0x10f0ae045 -[UIWindow addRootViewControllerViewIfPossible]
Oct 22 23:54:52 Li-Chengs-Mini demo[1283]: 6   0x10f0ae796 -[UIWindow _setHidden:forced:]
Oct 22 23:54:52 Li-Chengs-Mini demo[1283]: 7   0x10f0c20a9 -[UIWindow makeKeyAndVisible]
Oct 22 23:54:52 Li-Chengs-Mini demo[1283]: 8   0x10e4edd2d ffi_call_unix64
Oct 22 23:54:52 Li-Chengs-Mini demo[1283]: 9   0x129b85350
Oct 22 23:54:52 Li-Chengs-Mini demo[1283]: file:///app/tns_modules/ui/builder/builder.js:162:56: JS ERROR Error: Building UI from XML. @file:///app/main-page.xml:15:25
	 ↳Module '/Users/atai/Library/Developer/CoreSimulator/Devices/4CB95E45-B758-4000-85C5-5D8165CFA3B6/data/Containers/Bundle/Application/A8954754-DEDB-40A4-AFB6-9C6FCFB5716E/demo.app/app/nativescript-checkbox' not found for element 'nativescript-checkbox:CheckBox'.
	   ↳Could not find module '/Users/atai/Library/Developer/CoreSimulator/Devices/4CB95E45-B758-4000-85C5-5D8165CFA3B6/data/Containers/Bundle/Application/A8954754-DEDB-40A4-AFB6-9C6FCFB5716E/demo.app/app/nativescript-checkbox'. Computed path '/Users/atai/Library/Developer/CoreSimulator/Devices/4CB95E45-B758-4000-85C5-5D8165CFA3B6/data/Containers/Bundle/Application/A8954754-DEDB-40A4-AFB6-9C6FCFB5716E/demo.app/app/nativescript-checkbox'.
Oct 22 23:54:52 Li-Chengs-Mini com.apple.CoreSimulator.SimDevice.4CB95E45-B758-4000-85C5-5D8165CFA3B6.launchd_sim[834] (UIKitApplication:org.nativescript.demo[0x8c4][1283]): Service exited due to Segmentation fault: 11


note the string "nativescript-checkbox' not found for element 'nativescript-checkbox:CheckBox"

**Comment by bradmartin** [comment] 2016-10-25 18:32
Please share your markup. Thanks

**Comment by andy-tai** [comment] 2016-10-29 21:21
@bradmartin I was just using the demo program as is from the master branch, no modification

**Comment by bradmartin** [comment] 2016-10-29 22:18
I can't reproduce this. I'll try again, what about your package.json, please share that.

**Comment by bradmartin** [comment] 2016-10-29 22:18
I can't reproduce this. I'll try again, what about your package.json, please share that.

**Comment by andy-tai** [comment] 2016-10-30 08:06
contents of package.json:

{
  "nativescript": {
    "id": "org.nativescript.demo",
    "tns-android": {
      "version": "2.3.0"
    },
    "tns-ios": {
      "version": "2.3.0"
    }
  },
  "dependencies": {
    "nativescript-checkbox": "file:..",
    "tns-core-modules": "^2.3.0"
  },
  "devDependencies": {
    "babel-traverse": "6.7.6",
    "babel-types": "6.7.7",
    "babylon": "6.7.0",
    "filewalker": "0.1.2",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "^1.8.10",
    "tns-platform-declarations": "2.0.0"
  }
}

**Comment by bradmartin** [comment] 2016-10-30 17:25
I just realized you mentioned Angular @andy-tai - please see the README for angular sample. I also have no issues running the demo or the plugin in apps myself. I'm closing this, if still an issue for anyone then we can reopen or create a new issue to investigate.

**Closed by bradmartin** 2016-10-30 17:25 UTC
